[connections.snowflake]
account = "YGSQUSM-OH51192"
user = "YASHHSAY17402"
password = "Yashgupta17402@gmail.com" # Your actual password
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "CULTURE_HERITAGE"
schema = "PUBLIC"